### ISSUE TITLE
Support custom UserVoice domain name

### ISSUE THREAD

**Issue by Morgma** [Microsoft/vsts-uservoice-ui-extension#1]
We have aliased our domain for <account>.uservoice.com. They allow you to do this on paid subscriptions. 

The problem is that when we link to a VSTS work item from UserVoice, it now supplies our aliased domain name, which works with their API and their integration, but this extension is specifically looking for hyperlinks following a convention of "*.uservoice.com"

While our domain alias still happens to contain the word "uservoice" I know that's not always going to be the case for all accounts.

Maybe fallback to checking the hyperlink route format matches this pattern?
"/fourms/{[0-9]+:[0-9]+}/suggestion/{[0-9]+:[0-9]+}"

The non-aliased hyperlinks still work even with the custom domain so upon match, you could still use:
<account_name>.uservoice.com/{matched_route} 
to acquire the content for the work item details.

**Comment by ewaldhofman** [comment]
I like that suggestion. Will make the update shortly. Thanks for the feedback
